srobo/astoria

docs/conf.py
Adds a .nojekyll file to the github pages output, meaning that `_static` is not ignored.
=> docs: Fix formatting on GitHub pages

astoria.toml
This makes the example configuration file suitable for use in packaging
=> Use localhost as default broker IP address

debian/py3dist-overrides
=> debian: Add out-of-distro packages to py3dist-overrides

astoria/common/consumer.py, astoria/consumers/astctl/command.py
This means that consumers can now have persistent names, which will be
required for any consumer that runs as a daemon (e.g astwifid)
=> consumer: remove name_prefix abstract method

astoria/common/bundle.py, astoria/managers/astprocd.py, tests/common/test_bundle.py, tests/managers/astprocd/test_usercode_lifecycle.py
Fixes #63
- Uses exceptions to handle warnings in code bundle
- Print them into the logs
- Test them
=> astprocd: Log warnings to user accessible locations

astoria/consumers/astctl/metadata/show.py
Fixes #29
```
$ astctl metadata show                                                                                                                      
Current Astoria Metadata is:
arch: x86_64
arena: A
astoria_version: 0.2.0
game_timeout: None
kernel_version: 5.10.35-1-lts
kit_name: Astoria Development
kit_version: 0.0.0.0dev
libc_ver: glibc2.33
mode: RobotMode.DEV
python_version: 3.9.5
wifi_enabled: True
wifi_password: None
wifi_ssid: None
zone: 0
```
=> astctl: Sort output of metadata show

astoria/managers/astprocd.py, tests/managers/astprocd/test_usercode_lifecycle.py
Timestamps are marked from the start of code exec. Fixes #66 
Example:
```
[0:00:00.000008] WARNING: Running on DEVELOPMENT BUILD
[0:00:00.000227] ⚠ Your kit software is unsupported and requires an update. Please update the kit software.
[0:00:00.000280] === LOG STARTED ===
[0:00:00.086970] Hello World
[0:00:00.086970] === LOG FINISHED ===
```
=> astprocd: Add timestamps to logs

astoria/consumers/astwifid.py, tests/data/hostapd/config.txt
Management Frame Protection (MFP / IEEE 802.11w) is a mandatory requirement for both the client and the AP when using WPA3. Most devices will refuse to connect without it.
=> astwifid: Enable MFP for WPA3

astoria/managers/astprocd.py
This prevents the end of log output from looking like this:
```
[0:00:02.665918] PowerBoard(SERIAL): Setting output 5 to False
[0:00:02.668290] MotorBoard(SERIAL): Setting motor 0 to BRAKE.
[0:00:02.670544] MotorBoard(SERIAL): Setting motor 1 to BRAKE.
[0:00:00.006757] === LOG FINISHED ===
=> astprocd: Recalculate time_passed before outputting log finish message

.gitignore, astoria.toml, astoria/common/config.py, astoria/managers/astmetad/metadata_manager.py, tests/data/config/missing_optional.toml
This means that you don't need to have `/var/srobo` on your computer to develop astoria. It also makes it a tad more configurable.
=> astmetad: Allow cache directory to be configured.

astoria.toml, astoria/common/config.py, astoria/common/messages/astmetad.py, astoria/managers/astmetad/metadata_disk_lifecycle.py, astoria/managers/astmetad/metadata_manager.py, astoria/managers/astprocd/process_manager.py, astoria/managers/astprocd/usercode_lifecycle.py, tests/common/messages/test_astmetad.py, tests/managers/astprocd/test_usercode_lifecycle.py
Fixes #114
Allows configuration of both a default entry point, and an override in `robot-settings.toml`.
```toml
team_tla = "ZZZ62643"
usercode_entrypoint = "robot.py"
wifi_psk = "ae12-6dfe-9e05"
wifi_region = "GB"
wifi_enabled = true
```
```toml
[astprocd]
default_usercode_entrypoint = "robot.py"
```
=> Read user code entry point from robot-settings.toml

astoria/managers/astdiskd/disk_manager.py
Before this change, on systems without dbus and UDisks, astdiskd would simply just hang forever, which is not ideal.
On systems with dbus and Udisks, it would hang until the UdisksProvider updated.
=> astdiskd: Send an initial update on startup

Dockerfile
dephell is deprecated and pip can now install from pyproject.toml
=> Use pip for installing dependencies in Dockerfile

astoria/astctl/command.py, astoria/astprocd/process_manager.py, astoria/astwifid.py, astoria/common/config/system.py, astoria/common/config/user.py, astoria/common/mqtt/broadcast_helper.py, astoria/common/mqtt/wrapper.py
This commit changes how we instantiate pydantic BaseModel objects and thus how we validate the data that astoria is handling.
Previously, we were unpacking the data into kwargs and passing it into the constructor: `MyModel(**data)`, which works fine in the case that the `data` object is a dictionary. However, we can also load other data types from JSON and TOML, such as lists:
```python
>>> a = [1, 2, 3]
>>> dict(**a)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: dict() argument after ** must be a mapping, not list
```
Hence, there are potential runtime issues if we use this mechanism to create objects.
This commit changes to using `pydantic.parse_obj_as`, which safely handles objects that are not dictionaries.
Functionally, the code performs almost …
=> Use pydantic.parse_obj_as instead of BaseModel(**data)

astoria/astprocd/process_manager.py, astoria/astprocd/usercode_lifecycle.py, astoria/common/metadata.py, tests/managers/astprocd/test_usercode_lifecycle.py
This change usings the string.Template templating engine to allow metadata to be inserted into the initial log lines at runtime.
This means that we can print the OS version and other information that Astoria is aware of in the log lines.
It should be noted that the metadata is the metadata at the time of the log being generated, so the arena, zone and other keys that may be updated by a metadata USB might not be accurate when the code first starts. This is because metadata USBs are often inserted after the robot has been turned on!
Fixes #156
This change also builds the path to #113, although doesn't resolve it until #163 is also merged.
=> Allow templating of metadata in initial_log_lines

astoria/astmetad/metadata_disk_lifecycle.py, astoria/common/config/system.py, astoria/common/config/user.py, poetry.lock, pyproject.toml, tests/common/test_config.py, tests/common/test_metadata.py, tests/consumers/astwifid/test_wifi_hotspot_lifecycle.py, tests/managers/astprocd/test_usercode_lifecycle.py, tests/managers/mixins/test_disk_handler.py
The toml library is unmaintained and has known bugs.
Additionally, the tomli library is being integrated into the stdlib in Python 3.11 (PEP 680), making it the best choice of toml library. When we drop support for Python 3.10 and below, we will no longer need tomli as a dependency.
It should be noted that tomli is a load-only TOML library, and we need a separate library (tomli-w) to generate TOML files.
Fixes #125
~(Also adds Python 3.11-dev to CI, but does not require it to pass)~
=> Use tomli and tomli-w instead of toml library

astoria/common/metadata.py, tests/common/messages/test_astmetad.py, tests/common/test_metadata.py, tests/data/os_version/arch, tests/data/os_version/fedora17, tests/data/os_version/poky
=> Include OS version info in metadata

astoria/common/metadata.py, tests/common/test_metadata.py
This shows up in the logs and also in the kit-ui. It's nice to not have it blank when developing.
=> metadata: Get OS info for Mac

astoria/astctl/usercode/log.py
We're adding our own newlines with print. This makes the gaps go away
=> astctl: Strip spurious newlines from log messages

astoria/astprocd/usercode_lifecycle.py
Closing the transport sends sigkill to the process which causes the process to end immediately without cleanup. This leaves the transport open and just waits up to 5 seconds for the process to exit after SIGTERM before sending SIGKILL.
Because there are other async tasks communicating with the process we cannot use process.communicate()
This does not totally fix the issue with make_safe not running when the code is killed but the rest of the fix will be implemented in sr-robot3.
=> Fix kill command immediately using SIGKILL

astoria/astwifid/__init__.py, astoria/astwifid/hotspot_lifecycle.py, astoria/astwifid/lifecycle.py, astoria/astwifid/wifi_manager.py, astoria/common/metadata.py, docs/implementation/managers/astwifid.rst, tests/consumers/astwifid/test_wifi_hotspot_lifecycle.py
Refactor astwifid to enable multiple lifecycles.
This work is a prerequisite to adding support for WiFi client lifecycles and arena connectivity.
The refactor also adds a missing Lock, so eliminates an unhandled race condition.
=> Refactor astwifid

astoria/astprocd/usercode_lifecycle.py
fsync flushes OS buffers to disk. See https://docs.python.org/3/library/os.html?highlight=buffered#os.fsync
=> Make log files sync to disk
