srobo/astoria

astoria/common/disk_constraints.py, docs/implementation/managers/astdiskd.rst, docs/usage.rst
=> docs: Information on Disk Identification and Constraints

astoria/managers/astmetad.py
=> astmetad: Replace references to mutation sources

astoria.toml, debian/astdiskd.service, debian/astmetad.service, debian/astprocd.service, debian/control, debian/python3-astoria.install, debian/python3-astoria.postinst, debian/python3-astoria.postrm, debian/rules
- systemd services
- Add astoria user to systemd
- Recommended packages (i.e mosquitto)
Fixes #39
=> debian: Various improvements to packaging

astoria/managers/astmetad.py
Add the wifi bits of the bundle.toml as metadata, so that it actually changes when a usercode usb is inserted / removed.
Based on the kjk/astwifid branch
=> astmetad: Get WiFi metadata from bundle.toml

astoria.toml, astoria/common/config.py, astoria/consumers/astwifid.py, tests/consumers/astwifid/test_wifi_hotspot_lifecycle.py, tests/data/config/missing_optional.toml, tests/data/hostapd/config.txt
=> astwifid: Add configuration option for bridge device

astoria.toml, astoria/common/config.py, astoria/consumers/astwifid.py, tests/consumers/astwifid/test_wifi_hotspot_lifecycle.py, tests/data/config/extraneous_fields.toml, tests/data/config/missing_optional.toml
=> astwifid: Add `enable_wpa3` config option

astoria/common/data_component.py, astoria/consumers/astctl/usercode/log.py
=> astctl: Exit usercode log command on SIGINT

astoria/managers/astmetad/metadata_cache.py, astoria/managers/astmetad/metadata_manager.py, tests/managers/astmetad/test_metadata_cache.py
=> astmetad: Implement cacheable attributes for WiFi

.github/workflows/pypi.yml
`PYPI_TOKEN` is in repo secrets. 
Note: This does not upload to GitHub releases as that seems to be a bit of a pain¬
=> actions: Upload to PyPI on release

astoria/common/manager_requests.py, astoria/consumers/astctl/__init__.py, astoria/consumers/astctl/static_disks/__init__.py, astoria/consumers/astctl/static_disks/add.py, astoria/consumers/astctl/static_disks/remove.py, astoria/consumers/astctl/static_disks/remove_all.py, astoria/managers/astdiskd/disk_manager.py, astoria/managers/astdiskd/static.py
=> astdiskd: Allow mounting of static disks

astoria/managers/astdiskd/disk_manager.py
This allows us to run astoria in Docker and on MacOS
=> disk_manager: Disable Udisks if DBus is not available

astoria/astprocd/usercode_lifecycle.py
=> Ignore invalid Unicode when reading log streams

astoria/astmetad/metadata_manager.py
Previously these were not handled and this resulted in the manager never replying to the requests
Fixes #139
=> astmetad: Handle ValidationErrors on Mutation Requests

.github/workflows/tests.yml, astoria/astdiskd/static.py, astoria/common/ipc/manager_requests.py, poetry.lock, pyproject.toml
- Also remove typing_extensions as a dependency
- Upgrade other dependencies to latest stable versions
=> Drop Python 3.6 and 3.7

astoria/astdiskd/udisks.py
=> Ignore UDisks drive_block with empty UUID

astoria/astprocd/usercode_lifecycle.py
Thanks for reporting this @PeterJCLaw, I'm somewhat surprised that this code even worked!
Fixes #148
=> astprocd: Pass fh explicitly into UsercodeLifecycle.logger.log

astoria.toml, astoria/astdiskd/disk_manager.py, astoria/common/config/system.py
=> astdiskd: Allow configuration of mount points to ignore

astoria/common/components/manager.py, astoria/common/mqtt/wrapper.py, tests/common/mqtt/test_wrapper.py
Please see commit messages for details
=> Various Fixes to code smells and bugs

tests/common/disks/test_type_calculator.py
This makes each case a separate test so that we can determine which cases have failed.
=> tests: Use pytest parametrization for disk type tests

astoria/astprocd/usercode_lifecycle.py
This means that we can avoid the need to loop constantly and theoretically react marginally quicker
=> Use asyncio Event instead of polling loop

astoria/common/disks/structs.py, astoria/common/disks/type_calculator.py, tests/common/disks/test_structs.py, tests/common/disks/test_type_calculator.py
We aren't using this and would like to be more specific in the future.
Fixes #178
=> Remove DiskType.UPDATE

astoria/astprocd/process_manager.py, astoria/astwifid.py, astoria/common/mixins/__init__.py, astoria/common/mixins/metadata_handler.py
Remove duplicate implementations of parsing in both astprocd and astwifid
=> mixins: Implement MetadataHandlerMixin
